spring:
  application:
    name: sydney-archive-be

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "${BE_URL}/login/oauth2/code/naver"
            scope:
              - name
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  crypto:
    aes-key: ${AES_KEY}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  frontend-base-url: ${FE_URL}
  cookie:
    secure: ${COOKIE_SECURE}
    same-site: ${COOKIE_SAME_SITE}
    path: ${COOKIE_PATH}
  login-session:
    login-session-timeout-sec: 300
  system:
    buffer-time-sec: 15
  sse:
    sse-timeout-sec: 300
    sse-heartbeat-interval-sec: 20
    sse-heartbeat-initial-delay-sec: 15

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}

admin:
  username: ${ADMIN_NAME}
  email: ${ADMIN_EMAIL}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.web: DEBUG
    org.springframework.messaging.simp.SimpMessagingTemplate: DEBUG
    #    org.springframework.messaging.simp.stomp.StompSubProtocolHandler: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG