spring:
  application:
    name: wishlist-be

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 2000

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.web: DEBUG
    org.springframework.messaging.simp.SimpMessagingTemplate: DEBUG
#    org.springframework.messaging.simp.stomp.StompSubProtocolHandler: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG