spring:
  application:
    name: wishlist-be

  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.web: DEBUG